export const HANDLE_MENU = "HANDLE_MENU";

export const GET_PRODUCTS = "GET_PRODUCTS";

export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const DECREASE_ITEM_FROM_CART = "DECREASE_ITEM_FROM_CART";
export const INCREASE_ITEM_FROM_CART = "INCREASE_ITEM_FROM_CART";
